### ISSUE TITLE
Can only view first email

### ISSUE THREAD

**Issue by map7** [shugo/mournmail#5]
I seem to only be able to view one email, and when I try to view the second email no buffer is shown or updated. I tried closing all buffers but that didn't help. I had to exit textbringer and go back in.

```
CONFIG[:mournmail_accounts] = {
  "fastmail.com" => {
    from: "Michael <[email]>",
    delivery_method: :smtp,
    delivery_options: {
      address: "smtp.fastmail.com",
      port: 587,
      domain: Socket.gethostname,
      user_name: "[email]",
      password: File.read("[passwd file]").chomp,
      authentication: "login",
      enable_starttls_auto: true
    },
    imap_host: "imap.fastmail.com",
    imap_options: {
      auth_type: "PLAIN",
      user_name: "[email]",
      password: File.read("[passwd file]").chomp,
      ssl: true
    },
    spam_mailbox: "spam",
    archive_mailbox_format: false
  }
}

```

**Comment by shugo** [comment]
Your account configuration looks fine.

What happens when typing `C-u s` (mournmail_summary_sync with `all` option) and `p` (summary_prefetch_command) in the `*summary*` buffer?
These commands fetch all emails and if you type `SPC` in the `*summary*` buffer, the mail should be displayed in the `*message*` buffer.

If it doesn't work, please rename ~/.mournmail/cache/fastmail.com to ~/.mournmail/cache/fastmail.com.old etc and try again.

**Comment by map7** [comment]
Using C-u s, then p, then SPC works.
I just assumed I could hit Return on the email and it work.
It's very fast and looks great.

**Comment by shugo** [comment]
Thanks for your confirmation.

I've added key bindings documentation to [README](https://github.com/shugo/mournmail/blob/main/README.md#key-bindings).
You can also see key bindings by `F1 b`.

Hope it helps.
